### ISSUE TITLE
Server migration

### ISSUE THREAD

**Issue by ctwhome** [Via-Appia/via-appia-online-viewer#5]
More info to come from Rends de Hond (he will send an email)

The current server will be permanently shut down on the 2nd of June, and it will delete all the current DB data as mention. 

We need to safely secure the data. See the login details in this  [document](https://nlesc.sharepoint.com/:w:/r/sites/Cat/_layouts/15/Doc.aspx?sourcedoc=%7B12786c9d-01f8-49e6-80e7-ef3a4f517ca5%7D&action=editnew)

Original email:

> Dear Dr Maurice de Kleijn
> 
> We hereby confirm the cancellation of your server to 02/06/2021.  
> Warning: During the cancellation, we at Hetzner will delete all the data on the server, and all data on any external drives. When we delete the data, it will be permanent.
> 
> The cancellation can be revoked via your Robot account under the "Cancellation" tab of the server.  
> Kind regards
> 
> Your Hetzner Online Team

**Comment by bpmweel** [comment]
I have downloaded most of the data from the home directory. I am uploading it to the team directory, but it's a few gigs so it takes a while.
